name: "Modding Runtime Update"
on: [push]
jobs:
  Update-Modding-Runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@master
        with:
          repository: sociallydistantgame/system-runtime
          token: ${{ secrets.AUTOMANAGING_TOKEN }}
          path: system-runtime
          ref: master
      - env:
          AUTOMANAGING_TOKEN: ${{ secrets.AUTOMANAGING_TOKEN }}
        run: |
          mv system-runtime/.git git-temp
          rm -rf system-runtime/*
          cp -R Packages/com.sociallydistant.framework/* system-runtime/
          mv git-temp system-runtime/.git
          cd system-runtime
          git config user.name "Socially Distant [bot]"
          git config user.email "github-actions-noreply@sociallydistantgame.com"
          git add .
          git commit -m "Runtime update [automated]"
          git push
