name: "Modding Runtime Update"
on: [push]
jobs:
  Update-Modding-Runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - env:
          GITHUB_TOKEN: ${{ secrets.AUTOMANAGING_TOKEN }}
        run: |
          git clone https://github.com/sociallydistantgame/system-runtime system-runtime; 
          mv system-runtime/.git git-temp;
          rm -rf system-runtime/*;
          cp -R Packages/com.sociallydistant.framework/* system-runtime/;
          mv git-temp system-runtime/.git;
          cp .gitignore system-runtime/.gitignore;
          cd system-runtime;
          git add .;
          git config --global user.name "Socially Distant [bot]";
          git config --global user.email "github-actions-noreply@sociallydistantgame.com";
          git commit -m "Runtime update";
          git push;
          echo ritchie;
