name: "Modding Runtime Update"
on: [push]
jobs:
  Update-Modding-Runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTOMANAGING_TOKEN }}
        with:
          source_file: Packages/com.sociallydistant.framework
          destination_repo: 'sociallydistantgame/system-runtime'
          user_name: "Socially Distant [bot]"
          user_email: "github-actions-noreply@sociallydistantgame.com"
          commit_message: "Runtime update [automatic]"
